[package]
name = "party_house_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
card_deck = "*"
clap = { version = "*", features = ["derive"] }
rand = "*"
clearscreen = "*"
better_default = "*"
nestify = "*"
